# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgfathom" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9b1641cb6b37955c5603bfb5d9918d5a01243b536de5d63e406f269ac9e17ca4"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f1bba03f5a92753dfb94c3520b4aadeccaada80f7a2de9fe18312ee5227005c"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40d517efe6bbc968cadea59217581608ed4589743014362e090333553d77467d"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b3905e64384e94053e8cd1e09c98b4f8160799eee8ea8a17cffafe56bfb4e63"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pgfathom"
  desc "Discovers and validates PostgreSQL relationships that exist in the data but were never declared"
  homepage "https://github.com/lvcas-dotcom/pgfathom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgfathom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgfathom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binaries are not signed or notarised, so this cask clears the macOS quarantine attribute on install. That bypasses a Gatekeeper check, and you should know that it does. Verify what you got against the checksums published with the release.
  EOS
end
