# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgfathom" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "8c7079621d8389fadb3d266ab5ea0bacbc0c8d53e069fd36ce103b81f3a3c0dc"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c6bb5ef81f55fde519355d6344acff0d17f52e5320797ae4e834a405a0be1bd3"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c869b620b665eaf65dd18de3e8ccd6a06061bb786a47c46c074879f3ddc824b6"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec49b3d1f97edad7e89aba9d5cf560145312b618d4d43f6deb0e8ecc068c1972"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pgfathom"
  desc "Discovers and validates PostgreSQL relationships that exist in the data but were never declared"
  homepage "https://github.com/lvcas-dotcom/pgfathom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgfathom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgfathom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binaries are not signed or notarised, so this cask clears the macOS quarantine attribute on install. That bypasses a Gatekeeper check, and you should know that it does. Verify what you got against the checksums published with the release.
  EOS
end
