# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgfathom" do
  version "0.1.0-rc.2"

  on_macos do
    on_intel do
      sha256 "1b145f521ccf89efe6a4341f466e621446f769a99049319bb96da7b8af132081"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "984b1ff745f2ee71b7ceba11deb3c340de3189721022b8f6fbccad80afcd15c1"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e8fadf23eec87e72d28b7d56d7a8e853fed07bb74611140125d9f574b7b51eb"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfec72beb4e399a0f278cab3130f2fab6d7a02f8b7548cef9dbae09651383f4d"
      url "https://github.com/lvcas-dotcom/pgfathom/releases/download/v#{version}/pgfathom_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pgfathom"
  desc "Discovers and validates PostgreSQL relationships that exist in the data but were never declared"
  homepage "https://github.com/lvcas-dotcom/pgfathom"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgfathom"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgfathom"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The binaries are not signed or notarised, so this cask clears the macOS quarantine attribute on install. That bypasses a Gatekeeper check, and you should know that it does. Verify what you got against the checksums published with the release.
  EOS
end
